<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #132A13; font-size: 13px; }
        .wrap { padding: 28px; }
        h1 { font-size: 22px; margin: 0 0 4px; color: #4F772D; }
        .muted { color: #31572C; }
        table { width: 100%; border-collapse: collapse; margin-top: 24px; }
        th, td { border: 1px solid #90A955; padding: 10px; text-align: left; }
        th { background: #F4F3EE; }
        .right { text-align: right; }
        .footer { margin-top: 36px; font-size: 11px; color: #31572C; }
    </style>
</head>
<body>
<div class="wrap">
    <h1>Wama AI Invoice</h1>
    <p class="muted">Invoice draft</p>

    <p>
        <strong>Invoice #:</strong> {{ $invoice->invoice_number }}<br>
        <strong>Date:</strong> {{ optional($invoice->invoice_date)?->toDateString() }}<br>
        <strong>Due:</strong> {{ optional($invoice->due_date)?->toDateString() ?? '—' }}
    </p>

    <p>
        <strong>Bill to</strong><br>
        {{ $client?->company_name ?? '—' }}<br>
        {{ $client?->contact_person }}<br>
        {{ $client?->email }}<br>
        {{ $client?->mobile }}
    </p>

    <table>
        <thead>
        <tr>
            <th>Description</th>
            <th class="right">Amount (INR)</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Professional services / project milestone</td>
            <td class="right">{{ number_format((float) $invoice->amount, 2) }}</td>
        </tr>
        <tr>
            <td>Paid</td>
            <td class="right">{{ number_format((float) $invoice->paid_amount, 2) }}</td>
        </tr>
        <tr>
            <th>Balance due</th>
            <th class="right">{{ number_format(max(0, (float) $invoice->amount - (float) $invoice->paid_amount), 2) }}</th>
        </tr>
        </tbody>
    </table>

    <p><strong>Status:</strong> {{ ucfirst($invoice->payment_status) }}</p>
    <p class="footer">Generated by Wama AI · {{ now()->toDateTimeString() }}</p>
</div>
</body>
</html>
